# ----
# Site

title: The Kenyan Vegan
url: "https://thekenyanvegan.com/"
baseurl:
google_analytics_key: UA-126703908-1
newsletter_action:
disqus_shortname: thekenyanvegan

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Vegan lifestyle, health tips and whole food recipes... the Kenyan way.
author:
  name: The Kenyan Vegan
  email: the254vegan.gmail.com
  twitter: the_kenyanvegan
social:
  name: The Kenyan vegan
  links:
    - https://thekenyanvegan.com/

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-pwa-plugin

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# PWA
pwa:
  sw_src_filepath: service-worker.js
  sw_dest_filename: service-worker.js
  dest_js_directory: js
  precache_recent_posts_num: 5
  precache_glob_directory: /
  precache_glob_patterns:
  - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
  - index.html
  precache_glob_ignores:
  - sw-register.js
  - "fonts/**/*"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS